driver: com.mysql.jdbc.Driver
username: datasolutions
password: jukebox
serverlocation: jdbc:mysql://192.101.0.105/jukebox
sftphost: 192.168.0.101
sftpport: 22
sftpuser: pi
sftppass: raspberry
workingdir: /MusicLibrary
tempdir: temp/
httpserverdir: /home/pi/apps
server:
  applicationConnectors:
  - type: http
    port: 8085
  adminConnectors:
  - type: http
    port: 8086