driver: com.mysql.jdbc.Driver
username: datasolutions
password: jukebox
serverlocation: jdbc:mysql://192.168.0.105/jukebox
server:
  applicationConnectors:
  - type: http
    port: 8090
  adminConnectors:
  - type: http
    port: 8091